# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Ibl3PoWRiPjb3Km8yEL7xCkPsW5hB8p7FJOLCXEe1A2Xo2Db7mliF0Fr5jFO67kVG94hmJ757SOZ7+rLLL302kCSuzxYYU2SLRLoL225pWN+1+DpgAqinsycfB3Gkb3vecKVEP6aYMBrZmYI4EAtNnVuofoFJROaeMw2gptymZDhHXG86/seLKKXPHHjxnWPHYIGwJrhTZ4lfuhz7NkxK96j81p3oxEtXCJbm9YtnGB6fMeqWzJ7dn1nHsYO9MdqKgD+O/b8C6Pfbx2PsYgZySrmb7ogL+AEme6jpJ/ucHJgwHEbRnEHBWEngPwB7ODQHNMPpWNHeWpZZTtUGzZ9g66cYxx9sqqgRrRUe0tQI/TmJk0CqHZGzCEIRon4SU3W+E4DVu/PYRHP31ApwXv03fYvp1hk6Ep9a+lsDR/JibK8mOJlYJefEMW1dLtDPIluuZLdCCOoGmYyOG1KOAoF8Xt7p8wBBLNSbxbrV0PhDEe++kDuQVQV1z/qzYDWcnN+w2Qki7kA8r+wvD4zq3lgoOslF7hnqlTSJ0FzPTbrgGbCh2Xt2PgUDejZIWKUAjYTmx62t8/avoFG8KwShA4+Fzn8uXv+/kq1nWE+jIFUmZkkWZHnNHvhTevSo0xb7ggzI+HUUUhJwuAQ12UGoId3m28MeR2UGie/F/WQT/CJ9+c="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
