travis:
  secure:
    BINSTAR_TOKEN: IhZYmrFhWtBy38d4TaUdIOFJgrJhOen5zj7h/Tla7GvceHpY/2lMs7HlLYPC3wfmzCoiFqxNTea8iWHUECfaQnqIpPgsGq/nFes8tZ+ja3MN4xEGu9XdVJlr+1pg/aTmGO+KtLGaz8UzeDlahYSFQQX5G/tMbTNsFhb2P9+s1IBRtYAWpsXYX3MjNbnXIVRt9zMtNtlzVP5mjgkNk+K+ioXtMS3zgrrU+lUDg9ALtqQ/AeMpS4uf1uqV3Tasdzl3kZ4ZYW7vti2W9YiAdbURoq5LyUf48TKzHJYivYPVq6yDkGSBXvr55GPO57WiXJbOxz4VnHpsKMAyM+55m7bQeFJiD/igIqHMNrsam+qZ8qy350rjAz3QPOtVHuuQziETAQEkcsw149PR+EVWOsxQ3qm2W8Vp3AYWx7vOUtuapY/FE7O3++GXKGmSqL5SvnkZUWPL98b8N8ewRKSYwreuvE1b59H+5a5zs8CtJo7ayqcGK5ImgmkOcxwkVWj3NtybrNvTEsr08DT4Ib64oTrNAVV9GcDbpNVHKljTCZu866/EKy0T+gz9/wnDVW1NZDYl1F6odFLWtslUTIYazMGU5tqQSi4eu2CEvbjEw3OOGtkWvxy9S72pkMXJvOjw6fogvOsU6HwVxU7T9adkTMxFWO4YYp5e5flWMY8p8EImgVE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
